In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/uas-bigdata/The Emitten.csv


In [2]:
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv('../input/uas-bigdata/The Emitten.csv')
df.head()

Emitten    DER  Operating Profit Margin  Return On Asset  Sales Growth  \
0    ARGO  -1.82                   -59.18            -0.07         48.70   
1    BATA   0.63                   -78.25            -0.18        306.41   
2    BELL   1.05                     4.77             0.01        293.65   
3    BIMA  33.25                   -22.60            -0.12         27.82   
4    CNTX  -4.74                   -35.70            -0.13        200.76   

   Category  
0       2.0  
1       2.0  
2       2.0  
3       0.0  
4       2.0

In [4]:
df.drop(['Emitten'], axis=1, inplace=True)

In [5]:
np.asarray(df)


array([[-1.82000e+00, -5.91800e+01, -7.00000e-02,  4.87000e+01,
         2.00000e+00],
       [ 6.30000e-01, -7.82500e+01, -1.80000e-01,  3.06410e+02,
         2.00000e+00],
       [ 1.05000e+00,  4.77000e+00,  1.00000e-02,  2.93650e+02,
         2.00000e+00],
       [ 3.32500e+01, -2.26000e+01, -1.20000e-01,  2.78200e+01,
         0.00000e+00],
       [-4.74000e+00, -3.57000e+01, -1.30000e-01,  2.00760e+02,
         2.00000e+00],
       [ 2.80000e+00,  1.95200e+01,  2.00000e-02,  9.84720e+02,
         2.00000e+00],
       [ 2.74000e+00,  1.45900e+01,  3.00000e-02,  3.11560e+02,
         2.00000e+00],
       [-3.52300e+01, -3.15500e+01, -1.00000e-01,  8.95000e+00,
         1.00000e+00],
       [ 1.26000e+00,  1.53070e+02,  6.00000e-02,  3.90550e+03,
         3.00000e+00],
       [ 9.50000e-01,  7.80630e+02,  9.00000e-02,  9.15200e+01,
         2.00000e+00],
       [ 1.69000e+00,  2.56800e+01,  4.00000e-02,  4.64640e+02,
         1.00000e+00],
       [-3.74600e+01, -1.12340e+02, -6.0000

In [6]:
import statsmodels.api as sm

In [7]:
x = df.drop('Category', axis=1)
x.head()

DER  Operating Profit Margin  Return On Asset  Sales Growth
0  -1.82                   -59.18            -0.07         48.70
1   0.63                   -78.25            -0.18        306.41
2   1.05                     4.77             0.01        293.65
3  33.25                   -22.60            -0.12         27.82
4  -4.74                   -35.70            -0.13        200.76

In [8]:
y = df['Category']
y.head()

0    2.0
1    2.0
2    2.0
3    0.0
4    2.0
Name: Category, dtype: float64

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [10]:
x_train_sm = sm.add_constant(x_train)
x_train_sm

const    DER  Operating Profit Margin  Return On Asset  Sales Growth
14    1.0  -1.24                   -50.35            -0.02        38.081
18    1.0   0.75                    67.41             0.13       158.480
6     1.0   2.74                    14.59             0.03       311.560
21    1.0   0.47                     0.24             0.04        52.790
15    1.0   4.38                   -52.05            -0.03       102.870
9     1.0   0.95                   780.63             0.09        91.520
7     1.0 -35.23                   -31.55            -0.10         8.950
20    1.0   0.60                    12.30             0.01       770.850
13    1.0   0.52                    -2.05            -0.10        72.830
10    1.0   1.69                    25.68             0.04       464.640
17    1.0   1.75                    12.51             0.05       180.640
12    1.0   1.36                   249.69             0.03       727.480
16    1.0   2.98                   -34.78            -0.08       125.950
2     1.0   1.05                     4.77             0.01       293.650
1     1.0   0.63                   -78.25            -0.18       306.410
8     1.0   1.26                   153.07             0.06      3905.500
19    1.0   0.09                   131.80             0.04      2179.350

In [11]:
mnlogit_mod = sm.MNLogit(y_train, x_train_sm)
mnlogit_fit = mnlogit_mod.fit()

Optimization terminated successfully.
         Current function value: nan
         Iterations 16


/opt/conda/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:2299: RuntimeWarning: overflow encountered in exp
  eXB = np.column_stack((np.ones(len(X)), np.exp(X)))
/opt/conda/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:2300: RuntimeWarning: invalid value encountered in true_divide
  return eXB/eXB.sum(1)[:,None]


In [12]:
print (mnlogit_fit.summary())

                          MNLogit Regression Results                          
Dep. Variable:               Category   No. Observations:                   17
Model:                        MNLogit   Df Residuals:                        2
Method:                           MLE   Df Model:                           12
Date:                Tue, 05 Jul 2022   Pseudo R-squ.:                     nan
Time:                        15:21:49   Log-Likelihood:                    nan
converged:                       True   LL-Null:                       -15.573
Covariance Type:            nonrobust   LLR p-value:                       nan
             Category=1       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                          nan        nan        nan        nan         nan         nan
DER                            nan        nan        nan        nan         nan         nan


In [13]:
model = LogisticRegression(multi_class='auto')
model.fit(x_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [14]:
LogisticRegression()

LogisticRegression()

In [15]:
model.predict_proba(x_test)[0:5]

array([[2.13852496e-01, 3.51736827e-01, 3.67885440e-01, 6.65252364e-02],
       [1.73063928e-02, 5.68878242e-01, 2.64258695e-01, 1.49556670e-01],
       [1.80833490e-03, 3.20172898e-07, 9.98190075e-01, 1.27032171e-06],
       [2.81595124e-05, 9.93148756e-01, 2.13414724e-07, 6.82287087e-03],
       [6.74607083e-08, 3.74918809e-02, 8.72302052e-01, 9.02060000e-02]])

In [16]:
predictions = model.predict(x_test)
predictions

array([2., 1., 2., 1., 2.])

In [17]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       0.00      0.00      0.00         0
         2.0       0.67      0.67      0.67         3
         4.0       0.00      0.00      0.00         1

    accuracy                           0.40         5
   macro avg       0.17      0.17      0.17         5
weighted avg       0.40      0.40      0.40         5



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1

In [18]:
print(accuracy_score(y_test, predictions))

0.4
